### ISSUE TITLE
Argentinian ID not working

### ISSUE THREAD

**Issue by RodolfoEBDR** [PeculiarVentures/js-zxing-pdf417#15]
Hi! I'm developing an interpreter for the PDF417 code from argentinian IDs. I've try this library, but none seems to work. Could it be something about colour? Size? The pictures are FullHD, scanned... Is there a way to force the "TRY HARDER" mode when invoking the decoder? Thnaks!

**Comment by rmhrisk** [comment]
The decoder is very sensitive to image quality. Do you have a very high resolution sample to start from?

**Comment by rmhrisk** [comment]
Also check out this thread: https://github.com/PeculiarVentures/js-zxing-pdf417/issues/13

**Comment by RodolfoEBDR** [comment]
Thank you for your answer! Yes, I've changed the file pdf417/decoder/DecodedBitStreamParser.js but nothing changes.

**Comment by rmhrisk** [comment]
Im not sure what to tell you.

**Comment by seppo0010** [comment]
I was also trying an Argentinan ID and run into this problem, it might be related https://github.com/PeculiarVentures/js-zxing-pdf417/pull/16

**Comment by rmhrisk** [comment]
Merged.

I'm curious since your both trying for the same ID, what independently motivated you both down this path?

**Comment by seppo0010** [comment]
Well, the Argentinian ID has a PDF417 and it's not so uncommon to require one when registering for some services.

I'm trying a client-side instead of server-side to validate the image quality earlier in the process.

**Comment by rmhrisk** [comment]
You may find this interesting: https://demo.identityfront.com

We have not integrated the PDF417 library yet but MRZ is in the works currently.

**Comment by RodolfoEBDR** [comment]
I guess that @seppo0010 wants something to extract the data more than something to validate identity, just as we want.

**Comment by rmhrisk** [comment]
Yes, we also want extraction, we just decided to do MRZ first as we have higher confidence that we will be able to do it robustly.

PDF417 extraction is on the roadmap.

**Comment by RodolfoEBDR** [comment]
Also, and here is my personal toughts about the issue, here in Argentina we're used to try solutions that give us enough freedom to adapt, improve and also that won't affect out budget. That's another motivation for using XZing :)

**Comment by rmhrisk** [comment]
@RodolfoEBDR of course; that is universal and why we OSS so much of what we do :)

**Comment by tomasBustamante** [comment]
@RodolfoEBDR @seppo0010 Were you able to make it work?

**Comment by seppo0010** [comment]
It worked for me with the PR I sent that is now merged.

**Comment by seppo0010** [comment]
One thing I noticed using server-side zxing is that often resizing the original image (e.g.: 2x) helped a lot. I'm not sure if that's possible in the browser, I believe it is. However we did not go with this version for the project I was working on due to unrelated reasons.
