### ISSUE TITLE
Sample test page

### ISSUE THREAD

**Issue by SivaRamRIT** [PeculiarVentures/js-zxing-pdf417#2]
I am very much interested in this project. Could you guys please include a sample test page that shows how to call the correct pdf417 reader method with image as an input. Thanks

**Comment by rmhrisk** [comment]
SivaRamRIT, contact me at rmh at unmitigatedrisk.com

**Comment by tnyeanderson** [comment]
I would like to have something like this too. Maybe make a basic sample page with image upload that shows how to call everything and then commit it into an example folder? Or even better, update the readme with some basic instructions to get started?

**Comment by JimYan** [comment]
please show us the demo. TKS
